#!/bin/bash

if ! (source virtualenv/bin/activate && git diff --cached | pep8 --diff) then
	echo "Remeber to git-add the fixes before committing again!"
	exit 1
fi

IFS='
'

plus='^[+][\d]*'
message_send=0
for line in `git diff --check --cached`; do
	if [[ $message_send == 0 ]]; then
		echo "you have trailing whitespace left, please remove that before committing again!"
		echo -e "you can execute git diff --check to see a more colorful output\n"
		message_send=1
	fi
	if [[ $line =~ $plus ]]; then
		echo -e "\e[31m$line\e[0m"
	else
		echo -e "\033[0;34m$line\e[0m"
	fi
done
if [[ $message_send != 0 ]]; then
	exit 1
fi
