# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_customuser_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='value',
            field=models.TextField(verbose_name='value'),
        ),
    ]
