# Generated by Django 2.2.8 on 2020-01-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20190503_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
