# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import timelog.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, validators=[timelog.validators.date_is_present_or_past], verbose_name='Punch Start')),
            ],
            options={
                'verbose_name': 'Punch',
                'verbose_name_plural': 'Punches',
            },
        ),
        migrations.CreateModel(
            name='Timelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=-1, editable=False, verbose_name='Timelog number')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, validators=[timelog.validators.date_is_present_or_past], verbose_name='Start Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated:')),
                ('time', models.DurationField(validators=[timelog.validators.logged_time_is_positive], verbose_name='Time')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='issue.Issue', verbose_name='issue')),
            ],
            options={
                'verbose_name': 'timelog',
                'verbose_name_plural': 'timelogs',
                'ordering': ['created_at'],
            },
        ),
    ]
