# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0002_auto_20170714_0744'),
        ('timelog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_on', to=settings.AUTH_USER_MODEL, verbose_name='logger'),
        ),
        migrations.AddField(
            model_name='punch',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punched', to='issue.Issue', verbose_name='issue'),
        ),
        migrations.AddField(
            model_name='punch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punched_on', to=settings.AUTH_USER_MODEL, verbose_name='logger'),
        ),
    ]
