# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 07:44
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqnum', models.IntegerField(default=-1, editable=False, verbose_name='Sprint number')),
                ('startdate', models.DateField(blank=True, default=None, null=True, validators=[common.validators.date_is_present_or_future], verbose_name='Start_Date')),
                ('enddate', models.DateField(blank=True, default=None, null=True, validators=[common.validators.date_is_present_or_future], verbose_name='End_Date')),
                ('plandate', models.DateField(blank=True, default=None, null=True, validators=[common.validators.date_is_present_or_future], verbose_name='Planned Enddate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint', to='project.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'sprint',
                'verbose_name_plural': 'sprints',
                'base_manager_name': 'objects',
            },
        ),
    ]
