# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 07:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import search.fieldcheckings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4, 'A Projectname should be at least 4 chars long')], verbose_name='Name')),
                ('name_short', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are valid')], verbose_name='Short Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated:')),
                ('nextTicketId', models.IntegerField(default=1, editable=False, verbose_name='Next ticket ID')),
                ('nextSprintId', models.IntegerField(default=1, editable=False, verbose_name='Next sprint ID')),
                ('activity_only_for_managers', models.BooleanField(default=True, verbose_name='Only managers can see timelog statistics for all developers')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['name'],
            },
            bases=(search.fieldcheckings.SearchableMixin, models.Model),
        ),
    ]
