# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='project',
            name='currentsprint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectWhereWctive', to='sprint.Sprint', verbose_name='sprint'),
        ),
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.ManyToManyField(blank=True, related_name='dev_projects', to=settings.AUTH_USER_MODEL, verbose_name='developer'),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ManyToManyField(related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='project manager'),
        ),
    ]
