# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170714_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activity',
            field=models.TextField(default='{}'),
        ),
    ]
