# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='activity',
            field=models.TextField(default='[]'),
        ),
    ]
