# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('searchexpression', models.CharField(max_length=200, verbose_name='Expression')),
                ('persistent', models.BooleanField(default=False, verbose_name='Persistent')),
            ],
            options={
                'verbose_name': 'search',
                'verbose_name_plural': 'searches',
                'ordering': ['-pk'],
            },
        ),
    ]
