# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanbancol', '0002_kanbancolumn_project'),
        ('sprint', '0001_initial'),
        ('issue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assignee',
            field=models.ManyToManyField(blank=True, related_name='issues', to=settings.AUTH_USER_MODEL, verbose_name='assignee'),
        ),
        migrations.AddField(
            model_name='issue',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='issue',
            name='dependsOn',
            field=models.ManyToManyField(blank=True, related_name='dependent', to='issue.Issue', verbose_name='depends on'),
        ),
        migrations.AddField(
            model_name='issue',
            name='kanbancol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='kanbancol.KanbanColumn', verbose_name='status'),
        ),
        migrations.AddField(
            model_name='issue',
            name='participant',
            field=models.ManyToManyField(editable=False, related_name='discussing', to=settings.AUTH_USER_MODEL, verbose_name='participant'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='project.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='sprint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='sprint.Sprint', verbose_name='sprint'),
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='issues', to='tag.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issue.Attachment', verbose_name='attachment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issue.Issue', verbose_name='issue'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='issue',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issue.Issue', verbose_name='issue'),
        ),
    ]
