# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issue', '0001_initial'),
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notitype',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issue.Comment', verbose_name='issue'),
        ),
        migrations.AddField(
            model_name='notification',
            name='issue',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='issue.Issue', verbose_name='issue'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.ManyToManyField(related_name='notifications', to='discussion.Notitype', verbose_name='notitype'),
        ),
    ]
