# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import gitintegration.models
import search.fieldcheckings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Creation Date')),
                ('author', models.CharField(max_length=128, verbose_name='Author')),
                ('name', models.CharField(max_length=40, verbose_name='Commit name')),
                ('message', models.TextField(verbose_name='Commit message')),
                ('changes', models.TextField(blank=True, verbose_name='Changes')),
            ],
            options={
                'ordering': ['-date'],
            },
            bases=(search.fieldcheckings.SearchableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, validators=[gitintegration.models.validate_local_path], verbose_name='Repository URL')),
                ('rsa_priv_path', models.FileField(max_length=128, upload_to=gitintegration.models.get_upload_path, verbose_name='RSA private key')),
                ('rsa_pub_path', models.FileField(max_length=128, upload_to=gitintegration.models.get_upload_path, verbose_name='RSA public key')),
                ('conn_ok', models.BooleanField(default=False, verbose_name='Connection ok')),
                ('last_commit_processed', models.CharField(default='', max_length=40, verbose_name='Last commit processed')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
