# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issue', '0001_initial'),
        ('project', '0001_initial'),
        ('gitintegration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='project.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='commit',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='issue.Issue', verbose_name='Issue'),
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='gitintegration.Repository', verbose_name='Repository'),
        ),
        migrations.AlterUniqueTogether(
            name='commit',
            unique_together=set([('repository', 'name')]),
        ),
    ]
