# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitintegration', '0002_auto_20170714_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='tags',
            field=models.TextField(blank=True, verbose_name='Tags'),
        ),
    ]
