# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('position', models.IntegerField(verbose_name='position')),
                ('type', models.CharField(choices=[('ToDo', 'Todo'), ('InProgress', 'In Progress'), ('Done', 'Done')], default='ToDo', max_length=10, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'kanbancolumn',
                'verbose_name_plural': 'kanbancolumns',
                'ordering': ['position'],
            },
        ),
    ]
