# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=99, verbose_name='Typ')),
                ('queryset', models.CharField(max_length=999, verbose_name='Filter')),
                ('name', models.CharField(max_length=99, verbose_name='Name')),
            ],
        ),
    ]
